api_platform:
    formats:
        jsonld: ["application/ld+json"]
        json: ["application/json"]
    patch_formats:
        json: ["application/merge-patch+json"]
        jsonapi: ["application/vnd.api+json"]
    title: Hello API Platform
    version: 1.0.0
    defaults:
        pagination_client_enabled: false
        # pagination_items_per_page: 5
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
